######################################################################
# Automatically generated by qmake (3.0) Mon Jul 25 19:13:41 2016
######################################################################

TEMPLATE = app
TARGET = decipher_text
INCLUDEPATH += src/inc

#DIRS
DESTDIR=bin
OBJECTS_DIR=obj

# Input
SOURCES += src/main.cxx
SOURCES += src/Control/ControlData.cxx
SOURCES += src/Control/Setting.cxx
SOURCES += src/Interface/MainWindow.cxx

QT += widgets
QT += core
